= pets(1)
Emanuele Rocca
v1.0.0
:doctype: manpage
:manmanual: PETS
:mansource: PETS
:man-linkstyle: pass:[blue R < >]

== Name

pets - configuration management system for pets, not cattle

== Synopsis

*pets* [_OPTION_]...

== Options

*-conf-dir*=_DIR_::
  Read pets configuration from _DIR_.

*-debug*::
  Show debugging output.

*-dry-run*::
  Only show changes without applying them.

== Configuration Example

A pets configuration file setting up a minimal vimrc for root:

----
# pets: destfile=/root/.vimrc
# pets: package=vim

syntax on
set background=light
----

== Directives
Configuration directives are passed as key/value arguments, either on multiple
lines or separated by commas. The full list of supported directives is:

- destfile (mandatory) -- where to install this file. This is the only mandatory directive.
- symlink -- create a symbolic link to this file, instead of copying it like 'destfile' would.
- owner -- the file owner, passed to chown(1)
- group -- the group this file belongs to, passed to chgrp(1)
- mode -- octal mode for chmod(1)
- package -- which package to install before creating the file. This
  directive can be specificed more than once to install multiple packages.
- pre -- validation command. This must succeed for the file to be
  created / updated.
- post -- apply command. Usually something like reloading a service.

== Exit status

*0*::
  Success.
  Everything went according to the plan.

*1*::
  Failure.
  An important error occurred.

== Resources

*Project web site:* https://github.com/ema/pets

== Copying

Copyright (C) 2022 {author}. +
Free use of this software is granted under the terms of the MIT License.
