= PETS

A configuration management system for computers that are Pets, not Cattle.

This is for those who want to administer a few machines, all very different and
all Very Important. Those systems are not Cattle! They're actually a bit more
than Pets. They're almost Family. For example: a laptop, workstation, and
that personal tiny server in Sweden. They are all named after something dear.

== Design overview

The idea behind Pets is that Configuration Management shouldn't be harder than
administering a system by hand. Pets can be used without doing anything other
than modifying configuration files. Just locally run pets(1) after editing,
say, nginx.conf. The system applies the changes and reloads nginx. No need to
ssh somewhere, no puppetmaster to configure, nada.

Following from this basic idea, here are the design decisions:

- Runs locally on a single machine
- One directory holds the full configuration of the system
- No variables, no templates, just plain static config files
- No dependencies between different components (eg: updating file A if and
  after file B was updated)
- A single one-shot program reading the configuration directory and applying
  changes
- Changes are applied only if basic syntax checks pass
- Main interaction mechanism inspired by vim modelines

== How does it work

One example is worth a thousand words.

----
# pets: destfile=/etc/ssh/sshd_config, owner=root, group=root, mode=0644
# pets: package=ssh
# pets: package=openssh-client-dbgsym
# pets: pre=/usr/sbin/sshd -t -f
# pets: post=/bin/systemctl reload ssh.service
#
# Warning! This file has been generated by pets(1). Any manual modification
# will be lost.

Port 22
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Change to no to disable tunnelled clear text passwords
PasswordAuthentication no

X11Forwarding yes

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

Subsystem sftp /usr/lib/openssh/sftp-server

UsePAM yes
----

That's it! All supported configuration directives are showcased in the example above:

- destfile (mandatory) -- where to install this file and the relevant permissions. This is
  the only mandatory directive.
- owner -- the file owner, passed to chown(1)
- group -- the group this file belongs to, passed to chgrp(1)
- mode -- octal mode for chmod(1)
- package -- which package to install before creating the file. This
  directive can be specificed more than once to install multiple packages.
- pre -- validation command. This must succeed for the file to be
  created / updated.
- post -- apply command. Usually something like reloading a service.

Configuration directives are passed as key/value arguments, either on multiple
lines or separated by commas.

----
# pets: package=ssh, pre=/usr/sbin/sshd -t -f
----

The example above and the one below are equivalent

----
# pets: package=ssh
# pets: pre=/usr/sbin/sshd -t -f
----
